<?xml version="1.0" ?>
<testsuite name="unittest.loader._FailedTest-20240616161329" tests="3" time="0.000" failures="0" errors="3">
	<testcase classname="unittest.loader._FailedTest" name="-m" time="0.000">
		<error type="ImportError" message="Failed to import test module: -m
Traceback (most recent call last):
  File &quot;/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/loader.py&quot;, line 154, in loadTestsFromName
    module = __import__(module_name)
ModuleNotFoundError: No module named '-m'
"><![CDATA[ImportError: Failed to import test module: -m
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
ModuleNotFoundError: No module named '-m'

]]></error>
	</testcase>
	<testcase classname="unittest.loader._FailedTest" name="discover" time="0.000">
		<error type="ImportError" message="Failed to import test module: discover
Traceback (most recent call last):
  File &quot;/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/loader.py&quot;, line 154, in loadTestsFromName
    module = __import__(module_name)
ModuleNotFoundError: No module named 'discover'
"><![CDATA[ImportError: Failed to import test module: discover
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
ModuleNotFoundError: No module named 'discover'

]]></error>
	</testcase>
	<testcase classname="unittest.loader._FailedTest" name="unittest" time="0.000">
		<error type="TypeError" message="expected str, bytes or os.PathLike object, not NoneType"><![CDATA[Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/fnmatch.py", line 41, in fnmatch
    pat = os.path.normcase(pat)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/posixpath.py", line 54, in normcase
    return os.fspath(s)
TypeError: expected str, bytes or os.PathLike object, not NoneType
]]></error>
	</testcase>
	<system-out><![CDATA[]]></system-out>
	<system-err><![CDATA[]]></system-err>
</testsuite>
